name: Build and Deploy Unity Package

on:
  workflow_dispatch: #Manual trigger

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository containing Unity project
      - name: Checkout repository
        uses: actions/checkout@v2
            
      # Step 2: Run Unit Tests
      - name: Run Unit Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Assets/EmergenceSDK
          unityVersion: 2021.3.11f1
          packageMode: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}