name: Build and Deploy Unity Package

on:
  workflow_dispatch: #Manual trigger

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository containing Unity project
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Step 2: Cache Unity Packages
      - name: Cache Unity Packages
        uses: actions/cache@v2
        with:
          path: Library
          key: ${{ runner.os }}-Library-${{ hashFiles('**/Packages.lock') }}
          restore-keys: |
            ${{ runner.os }}-Library-

      # Step 3: Build Unity Package
      - name: Build Unity Package
        run: |
          mkdir -p build
          unity-editor \
            -projectPath . \
            -exportPackage "Assets/EmergenceSDK" "build/EmergenceSDK.unitypackage" \
            -logFile
      
      # Step 4: Include package.json
      - name: Include package.json
        run: |
          cp Assets/EmergenceSDK/package.json build/package.json # Adjust the path to your package.json file
      
      # Step 5: Upload the built Unity package and the package.json
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: unity-package
          path: build/
            
      # Step 6: Run Unit Tests
      - name: Run Unit Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Assets/EmergenceSDK
          unityVersion: 2021.3.11f1
          packageMode: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}